[cache]
max-size = 10485760
redis-addr = ''
redis-pass = ''

[cronjobs]
clean-files-interval = '1h'
clean-uploads-interval = '12h'
enable = true
folder-size-interval = '2h'

[db]
data-source = "postgresql://postgres:DARKXSIDE78@db.gvavwhtqpxmxvvuwvleb.supabase.co:5432/postgres"
log-level = 'info'
prepare-stmt = true

[db.pool]
enable = true
max-idle-connections = 25
max-lifetime = '10m'
max-open-connections = 25

[jwt]
session-time = '30d'
secret = '89bb03a8b5d4dd4163f32ee2a3d6f3db4034a61585f967bd906fe228910cf899'
allowed-users = [DARKXSIDE78]

[log]
level = 'info'
file = ''

[server]
graceful-shutdown = '10s'
port = 8080
read-timeout = '1h'
write-timeout = '1h'

[tg.uploads]
encryption-key = 'KxnACHT_v3x1GhyKNUW1PYLUAAmzq9Si'

[tg]
pool-size = 8
rate = 100
rate-burst = 5
ntp = false
disable-stream-bots = false
storage-file = ''
proxy = ''
rate-limit = true
reconnect-timeout = '5m'
