[db]
data-source = "postgresql://postgres.mzrowboqpoljiiawfmsh:DARKXSIDE78@aws-1-ap-south-1.pooler.supabase.com:5432/postgres"
prepare-stmt = false

[db.pool]
enable = false

[jwt]
allowed-users = ["KamiKaito", "WaifuKami", "OrewaRonin", "FraxxShadow", "GishinUnhara", "AnimeMonth"]
secret = "155da5dd439f7aa25959459dd39fe017"

[tg.uploads]
encryption-key = "xoD1IpJjNTfi0qo-JQPvQ5jbS3fdklII"

[tg]
pool-size = 8
rate = 100
rate-burst = 5
ntp = false
disable-stream-bots = false
rate-limit = true
reconnect-timeout = '5m'

[server]
listen = "0.0.0.0:8080"
